/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.Color;
import javax.swing.ImageIcon;
/**
 *
 * @author Farlo
 */
public class VCrearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form VCrearCuenta
     */
    public VCrearCuenta() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagen/logosisarchlogin.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btncrear = new javax.swing.JButton();
        btncuenta = new javax.swing.JButton();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtcargo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnsalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese Nombres:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 120, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese Contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 140, -1));

        btncrear.setBackground(new java.awt.Color(0, 0, 51));
        btncrear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncrear.setForeground(new java.awt.Color(255, 255, 255));
        btncrear.setText("Crear cuenta");
        btncrear.setBorder(null);
        btncrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btncrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 160, 50));

        btncuenta.setBackground(new java.awt.Color(255, 255, 254));
        btncuenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncuenta.setForeground(new java.awt.Color(0, 0, 51));
        btncuenta.setText("Iniciar sesión");
        btncuenta.setBorder(null);
        btncuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncuentaMouseExited(evt);
            }
        });
        jPanel1.add(btncuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        txtuser.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        txtuser.setForeground(new java.awt.Color(204, 204, 204));
        txtuser.setText("Registre su usuario");
        txtuser.setToolTipText("Registre su usuario");
        txtuser.setBorder(null);
        txtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtuserMousePressed(evt);
            }
        });
        jPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 180, 30));

        txtpass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpass.setForeground(new java.awt.Color(204, 204, 204));
        txtpass.setText("contraseña");
        txtpass.setToolTipText("Cree una contraseña");
        txtpass.setBorder(null);
        txtpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpassMousePressed(evt);
            }
        });
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 180, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 180, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 180, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("REGISTRE SUS DATOS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, 30));

        txtcargo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcargo.setForeground(new java.awt.Color(102, 102, 102));
        txtcargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "Administrador", "Usuario" }));
        txtcargo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtcargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(txtcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 180, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("¿Ya tienes cuenta?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 130, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Seleccione Cargo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, -1));

        txtnombre.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(204, 204, 204));
        txtnombre.setText("Registre sus Nombres");
        txtnombre.setToolTipText("Registre sus Nombres");
        txtnombre.setBorder(null);
        txtnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnombreMousePressed(evt);
            }
        });
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 180, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 180, 20));

        btnsalir.setBackground(new java.awt.Color(255, 255, 251));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_multiply_24px.png"))); // NOI18N
        btnsalir.setToolTipText("Salir");
        btnsalir.setBorder(null);
        btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir.setFocusable(false);
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 40, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/loginFondo.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/pantalla-de-portatil (2).png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMousePressed
        // TODO add your handling code here:
        if(txtuser.getText().equals("Registre su usuario")){
            txtuser.setText("");
            txtuser.setForeground(Color.black);
        }
        if(String.valueOf(txtpass.getPassword()).isEmpty()){
            txtpass.setText("contraseña");
            txtpass.setForeground(Color.lightGray);
        }
        if(txtnombre.getText().isEmpty()){
            txtnombre.setText("Registre sus Nombres");
            txtnombre.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_txtuserMousePressed

    private void txtpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpassMousePressed
        // TODO add your handling code here:
        if(String.valueOf(txtpass.getPassword()).equals("contraseña")){
            txtpass.setText("");
            txtpass.setForeground(Color.black);
        }
        if(txtuser.getText().isEmpty()){
            txtuser.setText("Registre su usuario");
            txtuser.setForeground(Color.lightGray);
        }
        if(txtnombre.getText().isEmpty()){
            txtnombre.setText("Registre sus Nombres");
            txtnombre.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_txtpassMousePressed

    private void btncuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncuentaMouseEntered
        // TODO add your handling code here:
        btncuenta.setForeground(new Color(102,0,153));
    }//GEN-LAST:event_btncuentaMouseEntered

    private void btncuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncuentaMouseExited
        // TODO add your handling code here:
        btncuenta.setForeground(new Color(0,0,51));
    }//GEN-LAST:event_btncuentaMouseExited

    private void txtnombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombreMousePressed
        // TODO add your handling code here:
        if(txtnombre.getText().equals("Registre sus Nombres")){
            txtnombre.setText("");
            txtnombre.setForeground(Color.black);
        }
        if(String.valueOf(txtpass.getPassword()).isEmpty()){
            txtpass.setText("contraseña");
            txtpass.setForeground(Color.lightGray);
        }
        if(txtuser.getText().isEmpty()){
            txtuser.setText("Registre su usuario");
            txtuser.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_txtnombreMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btncrear;
    public javax.swing.JButton btncuenta;
    public javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JComboBox<String> txtcargo;
    public javax.swing.JTextField txtnombre;
    public javax.swing.JPasswordField txtpass;
    public javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
