/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Farlo
 */
public class VLogin extends javax.swing.JFrame {

    /**
     * Creates new form VLogin
     */
    public VLogin() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagen/logosisarchlogin.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnytb = new javax.swing.JButton();
        btnfb = new javax.swing.JButton();
        btntwr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnentrar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        txtcargo = new javax.swing.JComboBox<>();
        btncrear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnytb.setBackground(new java.awt.Color(102, 0, 153));
        btnytb.setForeground(new java.awt.Color(51, 0, 102));
        btnytb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_YouTube_30px.png"))); // NOI18N
        btnytb.setBorder(null);
        btnytb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnytb.setFocusable(false);
        jPanel1.add(btnytb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        btnfb.setBackground(new java.awt.Color(102, 0, 153));
        btnfb.setForeground(new java.awt.Color(51, 0, 102));
        btnfb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Facebook_30px_3.png"))); // NOI18N
        btnfb.setBorder(null);
        btnfb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnfb.setFocusable(false);
        jPanel1.add(btnfb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        btntwr.setBackground(new java.awt.Color(102, 0, 153));
        btntwr.setForeground(new java.awt.Color(51, 0, 102));
        btntwr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_twitter_30px.png"))); // NOI18N
        btntwr.setBorder(null);
        btntwr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntwr.setFocusable(false);
        jPanel1.add(btntwr, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("INGRESE SUS DATOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 180, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 180, 20));

        txtuser.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        txtuser.setForeground(new java.awt.Color(204, 204, 204));
        txtuser.setText("Ingrese su usuario");
        txtuser.setToolTipText("Ingrese su usuario");
        txtuser.setBorder(null);
        txtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtuserMousePressed(evt);
            }
        });
        jPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 180, 30));

        txtpass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpass.setForeground(new java.awt.Color(204, 204, 204));
        txtpass.setText("contraseña");
        txtpass.setBorder(null);
        txtpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpassMousePressed(evt);
            }
        });
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 180, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_user_40px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_access_40px.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_protect_40px_1.png"))); // NOI18N
        jLabel4.setText("Login de Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logo sisarch login.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/loginFondo.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        btnentrar.setBackground(new java.awt.Color(0, 0, 51));
        btnentrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnentrar.setForeground(new java.awt.Color(255, 255, 255));
        btnentrar.setText("Entrar");
        btnentrar.setBorder(null);
        btnentrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnentrar.setFocusable(false);
        jPanel1.add(btnentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 120, 40));

        btnsalir.setBackground(new java.awt.Color(255, 255, 251));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_multiply_24px.png"))); // NOI18N
        btnsalir.setToolTipText("Salir");
        btnsalir.setBorder(null);
        btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir.setFocusable(false);
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 40, 40));

        txtcargo.setBackground(new java.awt.Color(0, 0, 50));
        txtcargo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcargo.setForeground(new java.awt.Color(204, 204, 204));
        txtcargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "Administrador", "Usuario" }));
        txtcargo.setBorder(null);
        txtcargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(txtcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 220, 30));

        btncrear.setBackground(new java.awt.Color(255, 255, 254));
        btncrear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncrear.setForeground(new java.awt.Color(0, 0, 51));
        btncrear.setText("Crear Cuenta");
        btncrear.setBorder(null);
        btncrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncrearMouseExited(evt);
            }
        });
        jPanel1.add(btncrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("¿No tienes cuenta?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMousePressed
        // TODO add your handling code here:
        if(txtuser.getText().equals("Ingrese su usuario")){
            txtuser.setText("");
            txtuser.setForeground(Color.black);
        }
        if(String.valueOf(txtpass.getPassword()).isEmpty()){
            txtpass.setText("contraseña");
            txtpass.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_txtuserMousePressed

    private void txtpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpassMousePressed
        // TODO add your handling code here:
        if(String.valueOf(txtpass.getPassword()).equals("contraseña")){
            txtpass.setText("");
            txtpass.setForeground(Color.black);
        }
        if(txtuser.getText().isEmpty()){
            txtuser.setText("Ingrese su usuario");
            txtuser.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_txtpassMousePressed

    private void btncrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncrearMouseEntered
        // TODO add your handling code here:
        btncrear.setForeground(new Color(102,0,153));
    }//GEN-LAST:event_btncrearMouseEntered

    private void btncrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncrearMouseExited
        // TODO add your handling code here:
        btncrear.setForeground(new Color(0,0,51));
    }//GEN-LAST:event_btncrearMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btncrear;
    public javax.swing.JButton btnentrar;
    public javax.swing.JButton btnfb;
    public javax.swing.JButton btnsalir;
    public javax.swing.JButton btntwr;
    public javax.swing.JButton btnytb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JComboBox<String> txtcargo;
    public javax.swing.JPasswordField txtpass;
    public javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
