/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.*;
/**
 *
 * @author Farlo
 */
public class VPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagen/loogo gore.png")).getImage());
    }
    public void color1(JButton p){
        p.setBackground(new Color(27,55,90));
        p.setForeground(Color.cyan);
    }
    public void color2(JButton p){
        p.setBackground(new Color(27,68,104));
        p.setForeground(Color.WHITE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombreUser = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnbasedatos = new javax.swing.JButton();
        btnusuario = new javax.swing.JButton();
        btninicio = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnreporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnx = new javax.swing.JButton();
        PanelBase = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(27, 68, 94));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/LOGO ANIVERSARIO.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 280, 240));

        nombreUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        nombreUser.setForeground(new java.awt.Color(255, 255, 255));
        nombreUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_male_user_30px_1.png"))); // NOI18N
        nombreUser.setText("NombreUser");
        jPanel2.add(nombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 190, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Custodiamos, conservamos y custodiamos");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 280, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("el patrimonio documental de la region");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 280, -1));

        btnbasedatos.setBackground(new java.awt.Color(27, 68, 104));
        btnbasedatos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnbasedatos.setForeground(new java.awt.Color(255, 255, 255));
        btnbasedatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_data_backup_24px.png"))); // NOI18N
        btnbasedatos.setText("Base de Datos");
        btnbasedatos.setBorder(null);
        btnbasedatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbasedatos.setFocusable(false);
        btnbasedatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbasedatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbasedatosMouseExited(evt);
            }
        });
        jPanel2.add(btnbasedatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 280, 52));

        btnusuario.setBackground(new java.awt.Color(27, 68, 104));
        btnusuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnusuario.setForeground(new java.awt.Color(255, 255, 255));
        btnusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_people_24px.png"))); // NOI18N
        btnusuario.setText("Usuarios");
        btnusuario.setBorder(null);
        btnusuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnusuario.setFocusable(false);
        btnusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnusuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnusuarioMouseExited(evt);
            }
        });
        jPanel2.add(btnusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 280, 52));

        btninicio.setBackground(new java.awt.Color(27, 68, 104));
        btninicio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btninicio.setForeground(new java.awt.Color(255, 255, 255));
        btninicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_home_24px.png"))); // NOI18N
        btninicio.setText("Inicio");
        btninicio.setBorder(null);
        btninicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btninicio.setFocusable(false);
        btninicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btninicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btninicioMouseExited(evt);
            }
        });
        jPanel2.add(btninicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 280, 52));

        btnsalir.setBackground(new java.awt.Color(27, 68, 104));
        btnsalir.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_emergency_exit_24px_1.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.setBorder(null);
        btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir.setFocusable(false);
        btnsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsalirMouseExited(evt);
            }
        });
        jPanel2.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 280, 52));

        btnreporte.setBackground(new java.awt.Color(27, 68, 104));
        btnreporte.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnreporte.setForeground(new java.awt.Color(255, 255, 255));
        btnreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_document_24px.png"))); // NOI18N
        btnreporte.setText("Reporte");
        btnreporte.setBorder(null);
        btnreporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreporte.setFocusable(false);
        btnreporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnreporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnreporteMouseExited(evt);
            }
        });
        jPanel2.add(btnreporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 280, 52));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/LOGO gorepa.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 720, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 880));

        jPanel3.setBackground(new java.awt.Color(27, 68, 94));

        btnx.setBackground(new java.awt.Color(27, 68, 94));
        btnx.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnx.setForeground(new java.awt.Color(255, 255, 255));
        btnx.setText("X");
        btnx.setBorder(null);
        btnx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnx.setFocusable(false);
        btnx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnxMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 1223, Short.MAX_VALUE)
                .addComponent(btnx, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1260, 40));

        javax.swing.GroupLayout PanelBaseLayout = new javax.swing.GroupLayout(PanelBase);
        PanelBase.setLayout(PanelBaseLayout);
        PanelBaseLayout.setHorizontalGroup(
            PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
        );
        PanelBaseLayout.setVerticalGroup(
            PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );

        jPanel1.add(PanelBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 1260, 840));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninicioMouseEntered
        // TODO add your handling code here:
        color1(btninicio);
    }//GEN-LAST:event_btninicioMouseEntered

    private void btninicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninicioMouseExited
        // TODO add your handling code here:
        color2(btninicio);
    }//GEN-LAST:event_btninicioMouseExited

    private void btnbasedatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbasedatosMouseEntered
        // TODO add your handling code here:
        color1(btnbasedatos);
    }//GEN-LAST:event_btnbasedatosMouseEntered

    private void btnbasedatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbasedatosMouseExited
        // TODO add your handling code here:
        color2(btnbasedatos);
    }//GEN-LAST:event_btnbasedatosMouseExited

    private void btnusuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusuarioMouseEntered
        // TODO add your handling code here:
        color1(btnusuario);
    }//GEN-LAST:event_btnusuarioMouseEntered

    private void btnreporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreporteMouseEntered
        // TODO add your handling code here:
        color1(btnreporte);
    }//GEN-LAST:event_btnreporteMouseEntered

    private void btnusuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusuarioMouseExited
        // TODO add your handling code here:
        color2(btnusuario);
    }//GEN-LAST:event_btnusuarioMouseExited

    private void btnreporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreporteMouseExited
        // TODO add your handling code here:
        color2(btnreporte);
    }//GEN-LAST:event_btnreporteMouseExited

    private void btnsalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseEntered
        // TODO add your handling code here:
        color1(btnsalir);
    }//GEN-LAST:event_btnsalirMouseEntered

    private void btnsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseExited
        // TODO add your handling code here:
        color2(btnsalir);
    }//GEN-LAST:event_btnsalirMouseExited

    private void btnxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnxMouseEntered
        // TODO add your handling code here:
        color1(btnx);
    }//GEN-LAST:event_btnxMouseEntered

    private void btnxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnxMouseExited
        // TODO add your handling code here:
        color2(btnx);
    }//GEN-LAST:event_btnxMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanelBase;
    public javax.swing.JButton btnbasedatos;
    public javax.swing.JButton btninicio;
    public javax.swing.JButton btnreporte;
    public javax.swing.JButton btnsalir;
    public javax.swing.JButton btnusuario;
    public javax.swing.JButton btnx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel nombreUser;
    // End of variables declaration//GEN-END:variables
}
