/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Panels;

/**
 *
 * @author Farlo
 */
public class PBaseDatos1 extends javax.swing.JPanel {

    /**
     * Creates new form PBaseDatos1
     */
    public PBaseDatos1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtbfol = new javax.swing.JTextField();
        txtbdec = new javax.swing.JTextField();
        txtblib = new javax.swing.JTextField();
        txtbnac = new javax.swing.JTextField();
        btnedit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtlib = new javax.swing.JTextField();
        txtaño = new javax.swing.JTextField();
        txtfol = new javax.swing.JTextField();
        txtmuni = new javax.swing.JTextField();
        txtdec = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtobs = new javax.swing.JTextArea();
        btnguardar = new javax.swing.JButton();
        btnmod = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setBackground(new java.awt.Color(204, 204, 204));
        tabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setRowHeight(25);
        tabla.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tabla.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 840, 260));

        txtbfol.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° de Folio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.add(txtbfol, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 130, -1));

        txtbdec.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Declarante", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.add(txtbdec, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 190, -1));

        txtblib.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° de Libro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.add(txtblib, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 130, -1));

        txtbnac.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre del Nacido", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.add(txtbnac, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 190, -1));

        btnedit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnedit.setForeground(new java.awt.Color(27, 68, 94));
        btnedit.setText("Editar");
        btnedit.setBorder(null);
        jPanel2.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 150, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 960, 390));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("N° de Libro");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 70, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Año acta de nacimiento");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("N° de Folio");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Municipalidad");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Declarante");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Nombre del Nacido");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Observaciones");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        txtlib.setBorder(null);
        jPanel3.add(txtlib, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 70, 20));

        txtaño.setBorder(null);
        jPanel3.add(txtaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 70, 20));

        txtfol.setBorder(null);
        jPanel3.add(txtfol, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 60, 20));

        txtmuni.setBorder(null);
        jPanel3.add(txtmuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 500, 20));

        txtdec.setBorder(null);
        jPanel3.add(txtdec, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 500, 20));

        txtnom.setBorder(null);
        jPanel3.add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 500, 20));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 51));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 500, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 51));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 60, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 51));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 70, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 51));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 70, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 51));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 500, 10));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 51));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 500, 10));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 51));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 500, 10));

        txtobs.setColumns(10);
        txtobs.setRows(5);
        jScrollPane2.setViewportView(txtobs);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 500, 110));

        btnguardar.setBackground(new java.awt.Color(27, 68, 94));
        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setText("Guardar");
        btnguardar.setBorder(null);
        jPanel3.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 140, 40));

        btnmod.setBackground(new java.awt.Color(27, 68, 94));
        btnmod.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnmod.setForeground(new java.awt.Color(255, 255, 255));
        btnmod.setText("Actualizar");
        btnmod.setBorder(null);
        jPanel3.add(btnmod, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 140, 40));

        btneliminar.setBackground(new java.awt.Color(204, 0, 0));
        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("Eliminar");
        btneliminar.setBorder(null);
        jPanel3.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 140, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 960, 370));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnnuevo.setBackground(new java.awt.Color(255, 255, 254));
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/nuevo-documento.png"))); // NOI18N
        btnnuevo.setText("Agregar Partida");
        btnnuevo.setBorder(null);
        btnnuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        btnbuscar.setBackground(new java.awt.Color(255, 255, 254));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/buscar.png"))); // NOI18N
        btnbuscar.setText("Buscar Partida");
        btnbuscar.setBorder(null);
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 120, 20));

        btnsalir.setBackground(new java.awt.Color(255, 255, 254));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/salida.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.setBorder(null);
        btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel4.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 80, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnbuscar;
    public javax.swing.JButton btnedit;
    public javax.swing.JButton btneliminar;
    public javax.swing.JButton btnguardar;
    public javax.swing.JButton btnmod;
    public javax.swing.JButton btnnuevo;
    public javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    public javax.swing.JTable tabla;
    public javax.swing.JTextField txtaño;
    public javax.swing.JTextField txtbdec;
    public javax.swing.JTextField txtbfol;
    public javax.swing.JTextField txtblib;
    public javax.swing.JTextField txtbnac;
    public javax.swing.JTextField txtdec;
    public javax.swing.JTextField txtfol;
    public javax.swing.JTextField txtlib;
    public javax.swing.JTextField txtmuni;
    public javax.swing.JTextField txtnom;
    public javax.swing.JTextArea txtobs;
    // End of variables declaration//GEN-END:variables
}
