/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Panels;

/**
 *
 * @author Farlo
 */
public class PBaseDatos extends javax.swing.JPanel {

    /**
     * Creates new form PBaseDatos
     */
    public PBaseDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablarep = new javax.swing.JTable();
        txtbdmndd = new javax.swing.JTextField();
        txtbdmndnt = new javax.swing.JTextField();
        txtbnexp = new javax.swing.JTextField();
        txtbaño = new javax.swing.JTextField();
        btnedit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtexp = new javax.swing.JTextField();
        txtaño = new javax.swing.JTextField();
        txtcaja = new javax.swing.JTextField();
        txtdmndt = new javax.swing.JTextField();
        txtdmndd = new javax.swing.JTextField();
        txtjuez = new javax.swing.JTextField();
        txtmateria = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtobs = new javax.swing.JTextArea();
        btnguardar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnmod = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablarep.setBackground(new java.awt.Color(204, 204, 204));
        tablarep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablarep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablarep.setRowHeight(25);
        tablarep.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tablarep.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tablarep);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 840, 260));

        txtbdmndd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Demandado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(txtbdmndd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 170, -1));

        txtbdmndnt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Demandante", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(txtbdmndnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 190, -1));

        txtbnexp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Exp", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(txtbnexp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 130, -1));

        txtbaño.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Año", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(txtbaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 140, -1));

        btnedit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnedit.setForeground(new java.awt.Color(27, 68, 94));
        btnedit.setText("Editar");
        btnedit.setBorder(null);
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 150, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 960, 390));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("N° de Expediente");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 100, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Año");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 60, 30, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("N° de caja");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Demandandante");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Demandado");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Juez");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Materia");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Observaciones");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        txtexp.setBorder(null);
        jPanel2.add(txtexp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 90, 20));

        txtaño.setBorder(null);
        jPanel2.add(txtaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 90, 20));

        txtcaja.setBorder(null);
        jPanel2.add(txtcaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 80, 20));

        txtdmndt.setBorder(null);
        jPanel2.add(txtdmndt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 500, 20));

        txtdmndd.setBorder(null);
        jPanel2.add(txtdmndd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 500, 20));

        txtjuez.setBorder(null);
        jPanel2.add(txtjuez, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 500, 20));

        txtmateria.setBorder(null);
        jPanel2.add(txtmateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 500, 20));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 51));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 500, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 51));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 80, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 51));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 90, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 51));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 90, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 51));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 500, 10));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 51));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 500, 10));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 51));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 500, 10));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 51));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 500, 10));

        txtobs.setColumns(10);
        txtobs.setRows(5);
        jScrollPane2.setViewportView(txtobs);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 500, 90));

        btnguardar.setBackground(new java.awt.Color(27, 68, 94));
        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setText("Guardar");
        btnguardar.setBorder(null);
        jPanel2.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 140, 40));

        btneliminar.setBackground(new java.awt.Color(204, 0, 0));
        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("Eliminar");
        btneliminar.setBorder(null);
        jPanel2.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 140, 40));

        btnmod.setBackground(new java.awt.Color(27, 68, 94));
        btnmod.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnmod.setForeground(new java.awt.Color(255, 255, 255));
        btnmod.setText("Actualizar");
        btnmod.setBorder(null);
        jPanel2.add(btnmod, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 140, 40));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 960, 370));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnnuevo.setBackground(new java.awt.Color(255, 255, 254));
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/nuevo-documento.png"))); // NOI18N
        btnnuevo.setText("Nuevo Registro");
        btnnuevo.setBorder(null);
        btnnuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        btnbuscar.setBackground(new java.awt.Color(255, 255, 254));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/buscar.png"))); // NOI18N
        btnbuscar.setText("Buscar Registro");
        btnbuscar.setBorder(null);
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 120, 20));

        btnsalir.setBackground(new java.awt.Color(255, 255, 254));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/salida.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.setBorder(null);
        btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel3.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 80, 20));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnbuscar;
    public javax.swing.JButton btnedit;
    public javax.swing.JButton btneliminar;
    public javax.swing.JButton btnguardar;
    public javax.swing.JButton btnmod;
    public javax.swing.JButton btnnuevo;
    public javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JTable tablarep;
    public javax.swing.JTextField txtaño;
    public javax.swing.JTextField txtbaño;
    public javax.swing.JTextField txtbdmndd;
    public javax.swing.JTextField txtbdmndnt;
    public javax.swing.JTextField txtbnexp;
    public javax.swing.JTextField txtcaja;
    public javax.swing.JTextField txtdmndd;
    public javax.swing.JTextField txtdmndt;
    public javax.swing.JTextField txtexp;
    public javax.swing.JTextField txtjuez;
    public javax.swing.JTextField txtmateria;
    public javax.swing.JTextArea txtobs;
    // End of variables declaration//GEN-END:variables
}
