/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Panels;

/**
 *
 * @author Farlo
 */
public class PUsuario extends javax.swing.JPanel {

    /**
     * Creates new form PUsuario
     */
    public PUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        pnltabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtbcar = new javax.swing.JTextField();
        txtbuser = new javax.swing.JTextField();
        txtbest = new javax.swing.JTextField();
        btnestado = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panelregis = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtcontra = new javax.swing.JTextField();
        txtcargo = new javax.swing.JComboBox<>();
        btnagregar = new javax.swing.JButton();
        txtnom = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnredit = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1260, 840));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnnuevo.setBackground(new java.awt.Color(255, 255, 254));
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/nuevo-documento.png"))); // NOI18N
        btnnuevo.setText("Nuevo Usuario");
        btnnuevo.setBorder(null);
        btnnuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        btnbuscar.setBackground(new java.awt.Color(255, 255, 254));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/buscar.png"))); // NOI18N
        btnbuscar.setText("Buscar Usuario");
        btnbuscar.setBorder(null);
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 120, 20));

        btnsalir.setBackground(new java.awt.Color(255, 255, 254));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/salida.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.setBorder(null);
        btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel4.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 80, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 20));

        pnltabla.setBackground(new java.awt.Color(255, 255, 255));
        pnltabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setBackground(new java.awt.Color(0, 102, 153));
        tabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabla.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tabla.setForeground(new java.awt.Color(255, 255, 255));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setGridColor(new java.awt.Color(30, 70, 110));
        tabla.setRowHeight(30);
        tabla.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tabla.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tabla);

        pnltabla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 840, 230));

        txtbcar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cargo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pnltabla.add(txtbcar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 170, -1));

        txtbuser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pnltabla.add(txtbuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, -1));

        txtbest.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pnltabla.add(txtbest, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 190, -1));

        btnestado.setBackground(new java.awt.Color(30, 70, 110));
        btnestado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnestado.setForeground(new java.awt.Color(255, 255, 255));
        btnestado.setText("Cambiar Estado");
        btnestado.setBorder(null);
        btnestado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnltabla.add(btnestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 120, 40));

        btneditar.setBackground(new java.awt.Color(30, 70, 110));
        btneditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btneditar.setForeground(new java.awt.Color(255, 255, 255));
        btneditar.setText("Editar");
        btneditar.setBorder(null);
        btneditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnltabla.add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 89, 36));

        jPanel1.add(pnltabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 960, 400));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        panelregis.setBackground(new java.awt.Color(30, 70, 110));
        panelregis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("INGRESE LOS  DATOS REQUERIDOS");
        panelregis.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuario");
        panelregis.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contraseña");
        panelregis.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cargo");
        panelregis.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        txtuser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelregis.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 310, 30));

        txtcontra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelregis.add(txtcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 310, 31));

        txtcargo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario" }));
        panelregis.add(txtcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 310, 30));

        btnagregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(0, 0, 51));
        btnagregar.setText("Agregar");
        btnagregar.setBorder(null);
        btnagregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelregis.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 89, 36));

        txtnom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelregis.add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 310, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombres");
        panelregis.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        btnredit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnredit.setForeground(new java.awt.Color(0, 0, 51));
        btnredit.setText("Actualizar");
        btnredit.setBorder(null);
        btnredit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelregis.add(btnredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 89, 36));

        btneliminar.setBackground(new java.awt.Color(204, 0, 0));
        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("Eliminar");
        btneliminar.setBorder(null);
        panelregis.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 90, 40));

        jPanel3.setBackground(new java.awt.Color(50, 100, 130));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/LOGO ANIVERSARIO.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("5 de Octubre, Cerro De Pasco 19001");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 210, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email: ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Visitanos en ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 260, 70, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("direccionarchivo@regionpasco.gob.pe");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 230, 220, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panelregis, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(panelregis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 960, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
    }//GEN-LAST:event_btnsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnagregar;
    public javax.swing.JButton btnbuscar;
    public javax.swing.JButton btneditar;
    public javax.swing.JButton btneliminar;
    public javax.swing.JButton btnestado;
    public javax.swing.JButton btnnuevo;
    public javax.swing.JButton btnredit;
    public javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel panelregis;
    public javax.swing.JPanel pnltabla;
    public javax.swing.JTable tabla;
    public javax.swing.JTextField txtbcar;
    public javax.swing.JTextField txtbest;
    public javax.swing.JTextField txtbuser;
    public javax.swing.JComboBox<String> txtcargo;
    public javax.swing.JTextField txtcontra;
    public javax.swing.JTextField txtnom;
    public javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
